### ISSUE TITLE
fine_dehalo bug

### ISSUE THREAD

**Issue by nobananasforyou** [Irrational-Encoding-Wizardry/vs-dehalo#42]
Hiya!

Calling fine dehalo with mask radius 2 introduces halos instead of removing it, however, this bug does not occur when the mask radius is 1.

Image Comparison:
https://slow.pics/c/1thqunQi

Script:
src = core.d2v.Source(r'you.d2v')
src = depth(src, 16)
src = fine_dehalo(src, darkstr=0, mask_radius=2, ss=2)
src = depth(src, 10)
src.set_output()

**Comment by Setsugennoao** [comment]
1) It's not adding halos, it's dehaloing less in that specific region
2) It's intended: https://slow.pics/c/FoMLIXVt, just a quirk of the gradient radius being bigger.
You can see that the edges are bigger, so it's just catching that faint halo near the edge as edge too since the radius is bigger. For lines this thin you should, well, use a small radius.
